version: '3.7'
name: simple-app-api
services:
  postgres:
    env_file: .env
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - postgres:/data/postgres
    ports:
      - ${DB_PORT:-5432}:5432
    networks:
      - simple-app-api
    restart: unless-stopped
  redis:
    env_file: .env
    container_name: redis
    image: redis:latest
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    environment:
      - REDIS_HOST=${REDIS_HOST:-localhost}
      - REDIS_USER=${REDIS_USER:-default}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
    ports:
      - ${REDIS_PORT:-6379}:6379
    networks:
      - simple-app-api
networks:
  simple-app-api:
    name: simple-app-api
    driver: bridge
volumes:
  postgres:
