name: CI PRODUCTION PIPELINE

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20.11.0
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  install:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Setup Node...
        uses: actions/checkout@v3
      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install pnpm
        run: npm install -g pnpm@8
      - name: Install dependencies...
        run: pnpm install --frozen-lockfile
        env:
          CI: true

  lint:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Install dependencies use cache...
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install pnpm
        run: npm install -g pnpm@8
      - name: Checking Linting...
        run: pnpm lint
        env:
          CI: true
